site_name: Hello Nextflow
repo_url: https://github.com/Sydney-Informatics-Hub/hello-nextflow-amsi24
repo_name: Sydney-Informatics-Hub/hello-nextflow-amsi24

nav:
  - Home: index.md
  - Setup: setup.md
  - Workshop content:  
    - 0. Introduction: content/00_intro.md
    - 1. Why Nextflow?: content/01_hellonextflow.md
    - 2. Hello World!: content/02_helloworld.md
    - 3. Your first pipeline: content/03_hellonf.md
    - 4. Outputs: content/04_output.md
    - 5. Inputs: content/05_inputs.md
    - 6. Parameters: content/06_params.md
    - 7. Adding processes: content/07_process.md
    - 8. Dynamic naming: content/08_dynamic.md
  - Supporting materials: resources.md

theme:
  name: material
  logo: assets/usyd-logo.png

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - attr_list
  - md_in_html
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-TNWWV3HK57
